import { ROLES, type Role } from "./users.roles";

const PERMISSION_EFFECTS = {
  ALLOW: "ALLOW",
  DENY: "DENY",
} as const;

const PERMISSIONS = {
  USERS: {
    CREATE_ANY: "USERS_CREATE_ANY",
    CREATE_NON_ADMIN: "USERS_CREATE_NON_ADMIN",
    READ_NON_ADMIN: "USERS_READ_NON_ADMIN",
    READ_ANY: "USERS_READ_ANY",
    UPDATE_SELF: "USERS_UPDATE_SELF",
    UPDATE_NON_ADMIN: "USERS_UPDATE_NON_ADMIN",
    UPDATE_ANY: "USERS_UPDATE_ANY",
    DELETE_NON_ADMIN: "USERS_DELETE_NON_ADMIN",
    DELETE_ANY: "USERS_DELETE_ANY",
  },
  TEMPLATES: {
    CREATE_ACCESSIBLE: "TEMPLATES_CREATE_ACCESSIBLE",
    READ_ACCESSIBLE: "TEMPLATES_READ_ACCESSIBLE",
    UPDATE_ACCESSIBLE: "TEMPLATES_UPDATE_ACCESSIBLE",
    DELETE_ACCESSIBLE: "TEMPLATES_DELETE_ACCESSIBLE",
    CREATE_ANY: "TEMPLATES_CREATE_ANY",
    READ_ANY: "TEMPLATES_READ_ANY",
    UPDATE_ANY: "TEMPLATES_UPDATE_ANY",
    DELETE_ANY: "TEMPLATES_DELETE_ANY",
  },
  SETTINGS: {
    READ_SELF: "SETTINGS_READ_SELF",
    UPDATE_SELF: "SETTINGS_UPDATE_SELF",
    READ_MODERATOR: "SETTINGS_READ_MODERATOR",
    UPDATE_MODERATOR: "SETTINGS_UPDATE_MODERATOR",
    READ_ANY: "SETTINGS_READ_ANY",
    UPDATE_ANY: "SETTINGS_UPDATE_ANY",
  },
  LOGS: {
    READ_ANY: "LOGS_READ_ANY",
  },
  REPORTS: {
    READ_SELF: "REPORTS_READ_SELF",
    READ_ACCESSIBLE: "REPORTS_READ_ACCESSIBLE",
    READ_ANY: "REPORTS_READ_ANY",
  },
  CONTRACTS: {
    CREATE_OWN: "CONTRACTS_CREATE_OWN",
    READ_ACCESSIBLE: "CONTRACTS_READ_ACCESSIBLE",
    UPDATE_ACCESSIBLE: "CONTRACTS_UPDATE_ACCESSIBLE",
    DELETE_ACCESSIBLE: "CONTRACTS_DELETE_ACCESSIBLE",
    ASSIGN_ANY: "CONTRACTS_ASSIGN_ANY",
    READ_ANY: "CONTRACTS_READ_ANY",
    UPDATE_ANY: "CONTRACTS_UPDATE_ANY",
    DELETE_ANY: "CONTRACTS_DELETE_ANY",
  },
  INVOICES: {
    CREATE_ACCESSIBLE: "INVOICES_CREATE_ACCESSIBLE",
    READ_ACCESSIBLE: "INVOICES_READ_ACCESSIBLE",
    UPDATE_ACCESSIBLE: "INVOICES_UPDATE_ACCESSIBLE",
    DELETE_ACCESSIBLE: "INVOICES_DELETE_ACCESSIBLE",
    READ_ANY: "INVOICES_READ_ANY",
    UPDATE_ANY: "INVOICES_UPDATE_ANY",
    DELETE_ANY: "INVOICES_DELETE_ANY",
  },
  PAYMENTS: {
    CREATE_ACCESSIBLE: "PAYMENTS_CREATE_ACCESSIBLE",
    READ_ACCESSIBLE: "PAYMENTS_READ_ACCESSIBLE",
    UPDATE_ACCESSIBLE: "PAYMENTS_UPDATE_ACCESSIBLE",
    DELETE_ACCESSIBLE: "PAYMENTS_DELETE_ACCESSIBLE",
    READ_ANY: "PAYMENTS_READ_ANY",
    UPDATE_ANY: "PAYMENTS_UPDATE_ANY",
    DELETE_ANY: "PAYMENTS_DELETE_ANY",
  },
  HOTELS: {
    CREATE_ANY: "HOTELS_CREATE_ANY",
    READ_ANY: "HOTELS_READ_ANY",
    UPDATE_ANY: "HOTELS_UPDATE_ANY",
    DELETE_ANY: "HOTELS_DELETE_ANY",
  },
  CLIENTS: {
    CREATE: "CLIENTS_CREATE",
    READ: "CLIENTS_READ",
    UPDATE: "CLIENTS_UPDATE",
    DELETE_ANY: "CLIENTS_DELETE_ANY",
  },
  DASHBOARD: {
    READ_SELF: "DASHBOARD_READ_SELF",
    READ_ACCESSIBLE: "DASHBOARD_READ_ACCESSIBLE",
    READ_ANY: "DASHBOARD_READ_ANY",
  },
} as const;

type ValueOf<T> = T[keyof T];
type PermissionEffect = ValueOf<typeof PERMISSION_EFFECTS>;
type Permission = ValueOf<{
  [Resource in keyof typeof PERMISSIONS]: ValueOf<(typeof PERMISSIONS)[Resource]>;
}>;

type PermissionOverride = {
  permission: Permission;
  effect: PermissionEffect;
};

type UserPermissionOverride = PermissionOverride & {
  user_id: string;
};

const ALL_PERMISSIONS = Object.freeze(
  Object.values(PERMISSIONS).flatMap((group) => Object.values(group)),
) as readonly Permission[];

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: ALL_PERMISSIONS,
  [ROLES.MODERATOR]: [
    PERMISSIONS.USERS.CREATE_NON_ADMIN,
    PERMISSIONS.USERS.READ_NON_ADMIN,
    PERMISSIONS.USERS.UPDATE_SELF,
    PERMISSIONS.USERS.UPDATE_NON_ADMIN,
    PERMISSIONS.USERS.DELETE_NON_ADMIN,
    PERMISSIONS.TEMPLATES.CREATE_ACCESSIBLE,
    PERMISSIONS.TEMPLATES.READ_ACCESSIBLE,
    PERMISSIONS.TEMPLATES.UPDATE_ACCESSIBLE,
    PERMISSIONS.TEMPLATES.DELETE_ACCESSIBLE,
    PERMISSIONS.SETTINGS.READ_SELF,
    PERMISSIONS.SETTINGS.UPDATE_SELF,
    PERMISSIONS.SETTINGS.READ_MODERATOR,
    PERMISSIONS.SETTINGS.UPDATE_MODERATOR,
    PERMISSIONS.LOGS.READ_ANY,
    PERMISSIONS.REPORTS.READ_ACCESSIBLE,
    PERMISSIONS.CONTRACTS.CREATE_OWN,
    PERMISSIONS.CONTRACTS.READ_ACCESSIBLE,
    PERMISSIONS.CONTRACTS.UPDATE_ACCESSIBLE,
    PERMISSIONS.CONTRACTS.DELETE_ACCESSIBLE,
    PERMISSIONS.CONTRACTS.ASSIGN_ANY,
    PERMISSIONS.INVOICES.CREATE_ACCESSIBLE,
    PERMISSIONS.INVOICES.READ_ACCESSIBLE,
    PERMISSIONS.INVOICES.UPDATE_ACCESSIBLE,
    PERMISSIONS.PAYMENTS.CREATE_ACCESSIBLE,
    PERMISSIONS.PAYMENTS.READ_ACCESSIBLE,
    PERMISSIONS.PAYMENTS.UPDATE_ACCESSIBLE,
    PERMISSIONS.PAYMENTS.DELETE_ACCESSIBLE,
    PERMISSIONS.HOTELS.CREATE_ANY,
    PERMISSIONS.HOTELS.READ_ANY,
    PERMISSIONS.HOTELS.UPDATE_ANY,
    PERMISSIONS.HOTELS.DELETE_ANY,
    PERMISSIONS.CLIENTS.CREATE,
    PERMISSIONS.CLIENTS.READ,
    PERMISSIONS.CLIENTS.UPDATE,
    PERMISSIONS.DASHBOARD.READ_ACCESSIBLE,
  ],
  [ROLES.EMPLOYEE]: [
    PERMISSIONS.USERS.UPDATE_SELF,
    PERMISSIONS.TEMPLATES.READ_ACCESSIBLE,
    PERMISSIONS.SETTINGS.READ_SELF,
    PERMISSIONS.SETTINGS.UPDATE_SELF,
    PERMISSIONS.REPORTS.READ_SELF,
    PERMISSIONS.CONTRACTS.CREATE_OWN,
    PERMISSIONS.CONTRACTS.READ_ACCESSIBLE,
    PERMISSIONS.CONTRACTS.UPDATE_ACCESSIBLE,
    PERMISSIONS.CONTRACTS.DELETE_ACCESSIBLE,
    PERMISSIONS.INVOICES.CREATE_ACCESSIBLE,
    PERMISSIONS.INVOICES.READ_ACCESSIBLE,
    PERMISSIONS.HOTELS.CREATE_ANY,
    PERMISSIONS.HOTELS.READ_ANY,
    PERMISSIONS.HOTELS.UPDATE_ANY,
    PERMISSIONS.HOTELS.DELETE_ANY,
    PERMISSIONS.CLIENTS.CREATE,
    PERMISSIONS.CLIENTS.READ,
    PERMISSIONS.CLIENTS.UPDATE,
    PERMISSIONS.DASHBOARD.READ_SELF,
  ],
} as const satisfies Record<Role, readonly Permission[]>;

function isPermission(value: string): value is Permission {
  return ALL_PERMISSIONS.includes(value as Permission);
}

function isPermissionEffect(value: string): value is PermissionEffect {
  return Object.values(PERMISSION_EFFECTS).includes(value as PermissionEffect);
}

function resolvePermissions(
  role: Role,
  overrides: readonly PermissionOverride[] = [],
): Permission[] {
  const permissions = new Set<Permission>(ROLE_PERMISSIONS[role]);

  for (const override of overrides) {
    if (override.effect === PERMISSION_EFFECTS.ALLOW) {
      permissions.add(override.permission);
      continue;
    }

    permissions.delete(override.permission);
  }

  return [...permissions];
}

function hasPermission(
  permissions: readonly Permission[] | null | undefined,
  permission: Permission,
): boolean {

  if (!permissions) return false;
  return permissions.includes(permission);
}

export {
  ALL_PERMISSIONS,
  PERMISSIONS,
  PERMISSION_EFFECTS,
  ROLE_PERMISSIONS,
  hasPermission,
  isPermission,
  isPermissionEffect,
  resolvePermissions,
  type Permission,
  type PermissionEffect,
  type PermissionOverride,
  type UserPermissionOverride,
};
