const REALTIME_WS_PATH = "/ws";
const REALTIME_HEARTBEAT_INTERVAL_MS = 30_000;
const REALTIME_URL_PARSE_BASE = "http://localhost";

export { REALTIME_HEARTBEAT_INTERVAL_MS, REALTIME_URL_PARSE_BASE, REALTIME_WS_PATH };
