-- Seed data: 100 fake hotels for local development.
-- Apply manually against tour_manager after hotels.sql DDL:
--   mysql -h 127.0.0.1 -P 3306 -u <user> -p tour_manager < server/core/sql/hotels.fake.sql

INSERT INTO hotels (name, stars, address, is_active) VALUES
  ('Sunrise Hostel Sofia #1', 3, '1 Vitosha Blvd, Sofia, Bulgaria', TRUE),
  ('Crystal Lodge Plovdiv #2', 5, '9 Unification Blvd, Plovdiv, Bulgaria', TRUE),
  ('Mountain Resort Varna #3', 2, '33 Musala St, Varna, Bulgaria', TRUE),
  ('Boutique Guest House Burgas #4', 4, '4 Transportna St, Burgas, Bulgaria', TRUE),
  ('Panorama Palace Bansko #5', 1, '6 Glazne St, Bansko, Bulgaria', TRUE),
  ('Harmony Suites Sozopol #6', 3, '3 Old Town Sq, Sozopol, Bulgaria', TRUE),
  ('Royal Spa Hotel Nessebar #7', 5, '7 South Beach Rd, Nessebar, Bulgaria', TRUE),
  ('Golden Retreat Veliko Tarnovo #8', 2, '4 Samovodska Charshia, Veliko Tarnovo, Bulgaria', TRUE),
  ('Alpine Inn Ruse #9', 4, '22 Slavyanski Blvd, Ruse, Bulgaria', FALSE),
  ('City Hotel Athens #10', 1, '5 Monastiraki Sq, Athens, Greece', TRUE),
  ('Imperial Hostel Thessaloniki #11', 0, '3 Aristotelous Sq, Thessaloniki, Greece', TRUE),
  ('Horizon Lodge Sofia #12', 5, '1 Vitosha Blvd, Sofia, Bulgaria', TRUE),
  ('Regent Resort Plovdiv #13', 6, '2 Kapitan Raycho St, Plovdiv, Bulgaria', TRUE),
  ('Park Guest House Varna #14', 4, '2 Han Krum St, Varna, Bulgaria', TRUE),
  ('Silver Palace Burgas #15', 1, '7 Aleksandrovska St, Burgas, Bulgaria', TRUE),
  ('Seaside Suites Bansko #16', 3, '15 Tsar Simeon St, Bansko, Bulgaria', TRUE),
  ('Plaza Spa Hotel Sozopol #17', 5, '9 Harmani Beach Rd, Sozopol, Bulgaria', TRUE),
  ('Continental Retreat Nessebar #18', 2, '1 Mesembria St, Nessebar, Bulgaria', FALSE),
  ('Serenity Inn Veliko Tarnovo #19', 4, '10 Stefan Stambolov Blvd, Veliko Tarnovo, Bulgaria', TRUE),
  ('Grand Hotel Ruse #20', 1, '6 Aleksandrovska St, Ruse, Bulgaria', TRUE),
  ('Sunrise Hostel Athens #21', 3, '10 Syntagma Sq, Athens, Greece', TRUE),
  ('Crystal Lodge Thessaloniki #22', 0, '12 Tsimiski St, Thessaloniki, Greece', TRUE),
  ('Mountain Resort Sofia #23', 2, '1 Vitosha Blvd, Sofia, Bulgaria', TRUE),
  ('Boutique Guest House Plovdiv #24', 4, '14 Main St, Plovdiv, Bulgaria', TRUE),
  ('Panorama Palace Varna #25', 1, '18 Slivnitsa Blvd, Varna, Bulgaria', TRUE),
  ('Harmony Suites Burgas #26', 6, '11 Bogoridi St, Burgas, Bulgaria', TRUE),
  ('Royal Spa Hotel Bansko #27', 5, '2 Pirin St, Bansko, Bulgaria', FALSE),
  ('Golden Retreat Sozopol #28', 2, '3 Old Town Sq, Sozopol, Bulgaria', TRUE),
  ('Alpine Inn Nessebar #29', 4, '7 South Beach Rd, Nessebar, Bulgaria', TRUE),
  ('City Hotel Veliko Tarnovo #30', 1, '4 Samovodska Charshia, Veliko Tarnovo, Bulgaria', TRUE),
  ('Imperial Hostel Ruse #31', 3, '22 Slavyanski Blvd, Ruse, Bulgaria', TRUE),
  ('Horizon Lodge Athens #32', 5, '88 Ermou St, Athens, Greece', TRUE),
  ('Regent Resort Thessaloniki #33', 0, '3 Aristotelous Sq, Thessaloniki, Greece', TRUE),
  ('Park Guest House Sofia #34', 4, '1 Vitosha Blvd, Sofia, Bulgaria', TRUE),
  ('Silver Palace Plovdiv #35', 1, '21 Hristo Botev Blvd, Plovdiv, Bulgaria', TRUE),
  ('Seaside Suites Varna #36', 3, '5 Primorski Blvd, Varna, Bulgaria', FALSE),
  ('Plaza Spa Hotel Burgas #37', 5, '4 Transportna St, Burgas, Bulgaria', TRUE),
  ('Continental Retreat Bansko #38', 2, '6 Glazne St, Bansko, Bulgaria', TRUE),
  ('Serenity Inn Sozopol #39', 6, '9 Harmani Beach Rd, Sozopol, Bulgaria', TRUE),
  ('Grand Hotel Nessebar #40', 1, '1 Mesembria St, Nessebar, Bulgaria', TRUE),
  ('Sunrise Hostel Veliko Tarnovo #41', 3, '10 Stefan Stambolov Blvd, Veliko Tarnovo, Bulgaria', TRUE),
  ('Crystal Lodge Ruse #42', 5, '6 Aleksandrovska St, Ruse, Bulgaria', TRUE),
  ('Mountain Resort Athens #43', 2, '5 Monastiraki Sq, Athens, Greece', TRUE),
  ('Boutique Guest House Thessaloniki #44', 0, '12 Tsimiski St, Thessaloniki, Greece', TRUE),
  ('Panorama Palace Sofia #45', 1, '1 Vitosha Blvd, Sofia, Bulgaria', FALSE),
  ('Harmony Suites Plovdiv #46', 3, '9 Unification Blvd, Plovdiv, Bulgaria', TRUE),
  ('Royal Spa Hotel Varna #47', 5, '33 Musala St, Varna, Bulgaria', TRUE),
  ('Golden Retreat Burgas #48', 2, '7 Aleksandrovska St, Burgas, Bulgaria', TRUE),
  ('Alpine Inn Bansko #49', 4, '15 Tsar Simeon St, Bansko, Bulgaria', TRUE),
  ('City Hotel Sozopol #50', 1, '3 Old Town Sq, Sozopol, Bulgaria', TRUE),
  ('Imperial Hostel Nessebar #51', 3, '7 South Beach Rd, Nessebar, Bulgaria', TRUE),
  ('Horizon Lodge Veliko Tarnovo #52', 6, '4 Samovodska Charshia, Veliko Tarnovo, Bulgaria', TRUE),
  ('Regent Resort Ruse #53', 2, '22 Slavyanski Blvd, Ruse, Bulgaria', TRUE),
  ('Park Guest House Athens #54', 4, '10 Syntagma Sq, Athens, Greece', FALSE),
  ('Silver Palace Thessaloniki #55', 0, '3 Aristotelous Sq, Thessaloniki, Greece', TRUE),
  ('Seaside Suites Sofia #56', 3, '1 Vitosha Blvd, Sofia, Bulgaria', TRUE),
  ('Plaza Spa Hotel Plovdiv #57', 5, '2 Kapitan Raycho St, Plovdiv, Bulgaria', TRUE),
  ('Continental Retreat Varna #58', 2, '2 Han Krum St, Varna, Bulgaria', TRUE),
  ('Serenity Inn Burgas #59', 4, '11 Bogoridi St, Burgas, Bulgaria', TRUE),
  ('Grand Hotel Bansko #60', 1, '2 Pirin St, Bansko, Bulgaria', TRUE),
  ('Sunrise Hostel Sozopol #61', 3, '9 Harmani Beach Rd, Sozopol, Bulgaria', TRUE),
  ('Crystal Lodge Nessebar #62', 5, '1 Mesembria St, Nessebar, Bulgaria', TRUE),
  ('Mountain Resort Veliko Tarnovo #63', 2, '10 Stefan Stambolov Blvd, Veliko Tarnovo, Bulgaria', FALSE),
  ('Boutique Guest House Ruse #64', 4, '6 Aleksandrovska St, Ruse, Bulgaria', TRUE),
  ('Panorama Palace Athens #65', 6, '88 Ermou St, Athens, Greece', TRUE),
  ('Harmony Suites Thessaloniki #66', 0, '12 Tsimiski St, Thessaloniki, Greece', TRUE),
  ('Royal Spa Hotel Sofia #67', 5, '1 Vitosha Blvd, Sofia, Bulgaria', TRUE),
  ('Golden Retreat Plovdiv #68', 2, '14 Main St, Plovdiv, Bulgaria', TRUE),
  ('Alpine Inn Varna #69', 4, '18 Slivnitsa Blvd, Varna, Bulgaria', TRUE),
  ('City Hotel Burgas #70', 1, '4 Transportna St, Burgas, Bulgaria', TRUE),
  ('Imperial Hostel Bansko #71', 3, '6 Glazne St, Bansko, Bulgaria', TRUE),
  ('Horizon Lodge Sozopol #72', 5, '3 Old Town Sq, Sozopol, Bulgaria', FALSE),
  ('Regent Resort Nessebar #73', 2, '7 South Beach Rd, Nessebar, Bulgaria', TRUE),
  ('Park Guest House Veliko Tarnovo #74', 4, '4 Samovodska Charshia, Veliko Tarnovo, Bulgaria', TRUE),
  ('Silver Palace Ruse #75', 1, '22 Slavyanski Blvd, Ruse, Bulgaria', TRUE),
  ('Seaside Suites Athens #76', 3, '5 Monastiraki Sq, Athens, Greece', TRUE),
  ('Plaza Spa Hotel Thessaloniki #77', 0, '3 Aristotelous Sq, Thessaloniki, Greece', TRUE),
  ('Continental Retreat Sofia #78', 6, '1 Vitosha Blvd, Sofia, Bulgaria', TRUE),
  ('Serenity Inn Plovdiv #79', 4, '21 Hristo Botev Blvd, Plovdiv, Bulgaria', TRUE),
  ('Grand Hotel Varna #80', 1, '5 Primorski Blvd, Varna, Bulgaria', TRUE),
  ('Sunrise Hostel Burgas #81', 3, '7 Aleksandrovska St, Burgas, Bulgaria', FALSE),
  ('Crystal Lodge Bansko #82', 5, '15 Tsar Simeon St, Bansko, Bulgaria', TRUE),
  ('Mountain Resort Sozopol #83', 2, '9 Harmani Beach Rd, Sozopol, Bulgaria', TRUE),
  ('Boutique Guest House Nessebar #84', 4, '1 Mesembria St, Nessebar, Bulgaria', TRUE),
  ('Panorama Palace Veliko Tarnovo #85', 1, '10 Stefan Stambolov Blvd, Veliko Tarnovo, Bulgaria', TRUE),
  ('Harmony Suites Ruse #86', 3, '6 Aleksandrovska St, Ruse, Bulgaria', TRUE),
  ('Royal Spa Hotel Athens #87', 5, '10 Syntagma Sq, Athens, Greece', TRUE),
  ('Golden Retreat Thessaloniki #88', 0, '12 Tsimiski St, Thessaloniki, Greece', TRUE),
  ('Alpine Inn Sofia #89', 4, '1 Vitosha Blvd, Sofia, Bulgaria', TRUE),
  ('City Hotel Plovdiv #90', 1, '9 Unification Blvd, Plovdiv, Bulgaria', FALSE),
  ('Imperial Hostel Varna #91', 6, '33 Musala St, Varna, Bulgaria', TRUE),
  ('Horizon Lodge Burgas #92', 5, '11 Bogoridi St, Burgas, Bulgaria', TRUE),
  ('Regent Resort Bansko #93', 2, '2 Pirin St, Bansko, Bulgaria', TRUE),
  ('Park Guest House Sozopol #94', 4, '3 Old Town Sq, Sozopol, Bulgaria', TRUE),
  ('Silver Palace Nessebar #95', 1, '7 South Beach Rd, Nessebar, Bulgaria', TRUE),
  ('Seaside Suites Veliko Tarnovo #96', 3, '4 Samovodska Charshia, Veliko Tarnovo, Bulgaria', TRUE),
  ('Plaza Spa Hotel Ruse #97', 5, '22 Slavyanski Blvd, Ruse, Bulgaria', TRUE),
  ('Continental Retreat Athens #98', 2, '88 Ermou St, Athens, Greece', TRUE),
  ('Serenity Inn Thessaloniki #99', 0, '3 Aristotelous Sq, Thessaloniki, Greece', FALSE),
  ('Grand Hotel Sofia #100', 1, '1 Vitosha Blvd, Sofia, Bulgaria', TRUE);
